version: "3.8"

services:

  accounts:
    image: mamadou4bah/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - mamadou4bah-network

  loans:
    image: mamadou4bah/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - mamadou4bah-network

  cards:
    image: mamadou4bah/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - mamadou4bah-network

networks:
  mamadou4bah-network: